name = "tazmondo/jest_roblox"
version = "3.19.1"
description = "A packaged distribution of Roblox's Jest implementation. May not be entirely accurate."
license = "MIT"
authors = ["Roblox", "paralov", "Tazmondo"]
repository = "https://github.com/Tazmondo/jest"
includes = ["pesde.toml", "README.md", "LICENSE", "Packages/**/*.luau"]

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
environment = "roblox"
lib = "Packages/init.luau"
build_files = ["Packages"]
